$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
    
  resources:
    type: object
    properties:
      ref:
        type: object
        properties:
          species:
            type: string
          release:
            type: string
          build:
            type: string

        required:
          - species
          - release
          - build
required:
  - samples
  - units
  - resources
